name       : haskell-text-conversions
version    : 0.3.0
release    : 1
source     :
    - https://hackage.haskell.org/package/text-conversions-0.3.0/text-conversions-0.3.0.tar.gz : 1756be2f6b515fea9e00b383c00d1ee851f8b25ddbc2901dd6be27d9b6292c21
license    : ISC
component  : programming.haskell
summary    : Safe conversions between textual types
description: |
    Safe conversions between textual types
builddeps  :
    - haskell-base16-bytestring-devel
    - haskell-base64-bytestring-devel
    - haskell-cabal-install
    - haskell-errors-devel
rundeps    :
    - devel:
        - haskell-base16-bytestring-devel
        - haskell-base64-bytestring-devel
        - haskell-errors-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
